/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using LostArk.Game.Messages.Structures;
using LostArkLogger;
using System;
using System.Collections.Generic;

namespace LostArk.Game.Messages.Definitions
{
    public class S_AuctionSearchResult
    {
        public S_AuctionSearchResult(BitReader reader)
        {
            Unk0 = reader.ReadInt32();
            Unk1 = reader.ReadInt32();
            Unk2 = reader.ReadInt32();
            Unk3 = new SearchDataList(reader);
        }

        public int Unk0 { get; }
        public int Unk1 { get; }
        public int Unk2 { get; }
        public SearchDataList Unk3 { get; } = new SearchDataList();
    }
}