/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArkLogger;

namespace LostArk.Game.Messages.Structures
{
    public class ProductData
    {
        public bool valid = false;
        internal ProductData()
        {
            //Made for conditional structures
        }

        internal ProductData(BitReader reader)
        {
            valid = true;
            Unk0 = reader.ReadInt64();
            Unk1 = reader.ReadInt64();
            Unk2 = reader.ReadInt64();
            Unk3 = new ItemData(reader);
            Unk4 = reader.ReadSimpleInt();
            Unk5 = reader.ReadByte();
            Unk6 = reader.ReadInt64();
            Unk7 = reader.ReadInt64();
            Unk8 = reader.ReadByte();
            Unk9 = reader.ReadInt64();
            Unk10 = reader.ReadInt64();
            Unk11 = reader.ReadByte();
        }

        public long Unk0 { get; }
        public long Unk1 { get; }
        public long Unk2 { get; }
        public ItemData Unk3 { get; } = new ItemData();
        public ulong Unk4 { get; }
        public byte Unk5 { get; }
        public long Unk6 { get; }
        public long Unk7 { get; }
        public byte Unk8 { get; }
        public long Unk9 { get; }
        public long Unk10 { get; }
        public byte Unk11 { get; }
    }
}