/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArkLogger;

namespace LostArk.Game.Messages.Structures
{
    public class SearchDataList
    {
        public bool valid = false;
        internal SearchDataList()
        {
            //Made for conditional structures
        }

        internal SearchDataList(BitReader reader)
        {
            valid = true;
            Unk0 = reader.ReadInt16();
            if(Unk0 <= 20)
            {
                for(var i = 0; i < Unk0; i++)
                {
                    Unk0_0_0.Add(new ProductData(reader));
                }
            }
        }

        public short Unk0 { get; }
        public List<ProductData> Unk0_0_0 { get; } = new List<ProductData>();
    }
}